#Create
POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Estevão Bilua",
    "email": "biluadev@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3333/sessions/password
Content-Type: application/json

{
    "email": "biluadev@gmail.com",
    "password": "12345678"
}
###
# Obter o perfil do usuário autenticado
GET http://localhost:3333/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMTI2OWMyYS04Mzg3LTRiMGQtOWU1Yi05YTVmYWZiYzhmYmIiLCJpYXQiOjE3MzgxNzM4NzcsImV4cCI6MTczODc3ODY3N30.yfrwUyPKoliqh7lQ80oxOYEg8xRznVAUlJqN-SvOc64
Content-Type: application/json
